language: java
jdk:
  - oraclejdk8

# whitelist
branches:
  only:
    - master
    - development

before_install:
  - mvn clean

after_success:
  - mvn clean test jacoco:report
  #- mvn replacer:replace 
  - mvn coveralls:report